# Copyright 2026 Asqav
# SPDX-License-Identifier: Apache-2.0
"""Regenerate the README vector list from manifest.json so it cannot drift.

The list lives between marker comments in verifier/conformance-vectors/README.md:

    <!-- vectors-list:start ... -->
    <!-- vectors-list:end -->

Everything between the markers is replaced with one line per manifest entry, in
manifest order: ``- `dir` — outcome (reason_code)`` (the parenthetical is
omitted when reason_code is empty). Run twice: the second run must be a
no-op, which is what makes the list drift-proof.

The list is an index, not a second copy of the notes. Each entry's `notes` text
stays in manifest.json, which is where it is authored and where the lock covers
it; rendering it here as well would make README a fourth copy of the same prose.

Usage: python verifier/render_vector_list.py
"""
from __future__ import annotations

import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
MANIFEST = _HERE / "conformance-vectors" / "manifest.json"
README = _HERE / "conformance-vectors" / "README.md"

START = "<!-- vectors-list:start (regenerated by verifier/render_vector_list.py; do not hand-edit) -->"
END = "<!-- vectors-list:end -->"


def _render(entries: list[dict]) -> list[str]:
    lines = []
    for entry in entries:
        outcome = entry["outcome"]
        if entry.get("reason_code"):
            outcome = f"{outcome} ({entry['reason_code']})"
        lines.append(f"- `{entry['dir']}` — {outcome}")
    return lines


def main() -> int:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit("README.md is missing the vectors-list marker comments")
    head, rest = text.split(START, 1)
    _old, tail = rest.split(END, 1)
    body = "\n".join(_render(entries))
    README.write_text(f"{head}{START}\n{body}\n{END}{tail}", encoding="utf-8")
    print(f"rendered {len(entries)} vector lines into {README.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
